name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # deploys on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # 5️⃣ Export static site
      - name: Export static site
        run: npm run export

      # 6️⃣ Add .nojekyll to prevent GitHub Pages issues
      - name: Add .nojekyll
        run: touch out/.nojekyll

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
